AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation Template for Kittens Carousel. It is a static website application 
  deployed on AWS Simple Storage Service (S3), served through 
  Cloudfront and Route 53 using AWS Cloudformation Service.
  
Parameters:
  DomainName:
    Description: DNS name of existing Amazon Route53 hosted zone
    Type: AWS::Route53::HostedZone::Id
  KittensDomainName:
    Description: Full domain name
    Type: String
  
  
Resources:
  KittensS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref KittensDomainName
      WebsiteConfiguration:
        IndexDocument: index.html
  KittensS3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref KittensDomainName #required
      PolicyDocument:  #required
       Statement:
        - Sid: PublicReadforStaticWebsite
          Effect: Allow 
          Principal: *
          Action: s3::GetObject
          Resource: !Join ['', ['arn::aws::s3:::', !Ref 'KittensS3Bucket', /*]]
          
  KittensCertificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      CertificateTransparencyLoggingPreference: ENABLED
      DomainName: !Ref KittensDomainName #required
      DomainValidationOptions:
        - DomainName: !Ref KittensDomainName
          HostedZoneId: !Ref DomainName 
      ValidationMethod: DNS 
  KittensDNSName:
    Type: "AWS::Route53::RecordSetGroup"
    Properties:
      HostedZoneId: !Ref DomainName 
      HostedZoneName: String
      RecordSets:
        - Name: !Ref KittensDomainName
          Type: A 
          AlliasTarget: 
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt KittensCloudfront.DomainName
  
  KittensCloudFront:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig: #required
        Aliases: !Ref KittensDomainName 
        Comment: Cloudfront Distribution
        DefaultCacheBehavior: 
          AllowedMethods: 
            - GET
            - HEAD
          Compress: true
          ForwardedValues: 
            QueryString: true
            Cookies:
              Forward: none
          TargetOriginId: KittensOrigin
          ViewerProtocolPolicy: allow-all
        Enabled: true 
        HttpVersion: http2
        Origins: 
          CustomOriginConfig: 
            CustomOriginConfig
          DomainName: String
          Id: String
          OriginCustomHeaders: 
            - OriginCustomHeader
        PriceClass: String
        Restrictions: 
          Restrictions
        ViewerCertificate: 
          ViewerCertificate
        WebACLId: String
      
  
         
  

  
Outputs: