version: "3.7"

services:
  database:
    image: mysql:5.7
    volumes:
      - /datadir:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: R1234r
            MYSQL_DATABASE: phonebook_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: Clarusway_1
            MYSQL_PORT: 3306
    networks: 
      - clarusnet

  myapp:
    image: 089319708029.dkr.ecr.us-east-1.amazonaws.com/e2011yahya/phonebook-app:latest
    deploy:
      mode: global
      update_config:
        parallelism: 2
        delay: 5s
        order: start-first
    depends_on:   
      -  database 
    ports: 
      -  80:80
    networks:
      -  clarusnet
      
  
networks:
  clarusnet:
    driver: overlay 
    
configs:
  initialdb:
    file: ./init.sql    

  