version: '3'

services:
   database:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: A1234a 
        MYSQL_DATABASE: bookstore_db
        MYSQL_USER: clarusway
        MYSQL_PASSWORD: Clarusway_1
      networks: 
        - clarusnet
   app:
      depends_on:
       - database
      build: .
      restart: always
      volumes:
        - /php/www:/var/www/html
      ports:
       - '80:80'
      networks:
       - clarusnet
networks:
   clarusnet:
      driver: bridge