AWSTemplateFormatVersion: 2010-09-09
Description: |
  The Phonebook Application aims to create a phonebook application 
  in Python and deployed as a web application with Flask on AWS 
  Application Load Balancer with Auto Scaling Group of Elastic 
  Compute Cloud (EC2) Instances and Relational Database Service(RDS)
  using AWS Cloudformation Service.


  
Resources:
  ALBsecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Allows HTTP (80) connections to Application Load Balancer
      SecurityGroupIngress:
        - FromPort: 80
          IpProtocol: tcp
          ToPort: 80
          CidrIp: 0.0.0.0/0
      #VpcId: String if not written stack makes it default
  WebserverSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Allows HTTP (80) connections only from the security group of Application Load Balancer     
      SecurityGroupIngress:
        - FromPort: 80
          IpProtocol: tcp
          ToPort: 80
          CidrIp: 0.0.0.0/0
          SourceSecurityGroupId: !GetAtt ALBsecurityGroup.GroupId
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - FromPort: 3306
          IpProtocol: Mysql/Aurora
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  RDS_SecurityGroup:
    Type: "AWS::RDS::DBSecurityGroup"
    Properties:
      DBSecurityGroupIngress: #required
        - FromPort: 3306
          IpProtocol: Mysql/Aurora
          ToPort: 3306
          CidrIp: 0.0.0.0/0
      GroupDescription: DataBasaSecurityGroup #required
      
          

  WebserverLaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateName: CFlaunchtemplate
      LaunchTemplateData:
        ImageId: ami-0947d2ba12ee1ff75
        InstanceType: t2.micro
        KeyName: ya_lin
        SecurityGroupIds: 
          - GetAtt WebserverSecurityGroup.GroupId
        TagSpecifications: 
          - ResourceType: instance
            Tags: 
            - Key: Name
              Value: !Sub Web Server of ${AWS::StackName}
        UserData: String
          Fn::Base64:
            !Sub |
              #! /bin/bash
              sudo yum update -y
              sudo yum install python3 -y
              sudo pip3 install flask


  ALBTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckEnabled: Yes
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      Port: 80
      Protocol: HTTP
      TargetType: instance
      VpcId: !GetAtt WebserverSecurityGroup.VpcId

  

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      SecurityGroups: 
        - !GetAtt ALBSecurityGroup.GroupId 
      Subnets: 
        - subnet-b5258a94
          subnet-4f5aae7e
          subnet-7248d27c
          subnet-acd575ca
          subnet-9876dbc7
          subnet-e182f2ac
      Type: application 
     
        
  ALBListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions: #required
        - TargetGroupArn: !Ref ALBTargetGroup
          Type: forward
      LoadBalancerArn: !Ref ApplicationLoadBalancer  #required
      Port: 80 #required
      Protocol: HTTP #required
      
  ALBAutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      AvailabilityZones:
        !GetAZs 
      DesiredCapacity: 2
      HealthCheckGracePeriod: 90
      HealthCheckType: ELB
      LaunchTemplate: 
        LaunchTemplateId: !Ref WebserverLaunchTemplate
        Version: !GetAtt WebserverLaunchTemplate.DefaultVersionNumber      
      MaxSize: 3 #required
      MinSize: 1 #required
      TargetGroupARNs:
        - !Ref ALBTargetGroup

  RDSinstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 20
      AssociatedRoles:
        - DBInstanceRole
      BackupRetentionPeriod: 7
      DBInstanceClass: db.t2.micro #required
      DBInstanceIdentifier: String
      DBName: PhonebookDatabase
      DBSecurityGroups: 
        - !GetAtt RDS_SecurityGroup.GroupId 
      DeleteAutomatedBackups: true
      DeletionProtection: true
      Engine: mysql
      EngineVersion: MySQL 8.0.20
      MasterUserPassword: P123456789
      MasterUsername: admin
      Port: 3306
      PreferredBackupWindow: "01:00-02:00" UTC
      PreferredMaintenanceWindow: "Sun:05:00-Sun:06:00" UTC
      PubliclyAccessible: true
      Tags:
        - Tag
      Timezone: String
      UseDefaultProcessorFeatures: Boolean
      VPCSecurityGroups:
        - String
  
  
Outputs:
  WebsiteURL:
    Value: !Sub 
      - http://${ALBAddress}
      - ALBAddress: !GetAtt ApplicationLoadBalancer.DNSName
    Description: Phonebook Application Load Balancer URL
  RDS-endpoint:
    Description: Phonebook DB endpoint
    Value: !Ref RDSinstance
    